// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "turb/legacy/settings/stat/metadata.hpp"

TEST_CASE( "Metadata - conversion to string - static", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Metadata - conversion to string - display all - static", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Metadata - conversion to string - extra indent size - static", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Metadata - conversion to string - extra indent level - static", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Metadata - conversion to string for empty - static", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

