// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "turb/legacy/settings/stat/parameters_conversion.hpp"

TEST_CASE( "Parameters - conversion from dynamic to static", "[settings][.][!mayfail]" )
{
    // TODO
    REQUIRE( false );
}
