// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include "turb/legacy/settings/execution_settings.hpp"

TEST_CASE("ExecutionSettings - Sample Test", "[sample]")
{
    vortex::turb::legacy::settings::ExecutionSettings( nullptr );

    REQUIRE(true);
}
