// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include "turb/legacy/settings/parameters.hpp"

TEST_CASE("Parameters - Sample Test", "[sample]")
{
    vortex::turb::legacy::settings::Parameters( nullptr );

    REQUIRE(true);
}
