// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wcovered-switch-default"

#include <cstring>
#include <string>

namespace vortex::runner::config
{

enum class ParallelStrategyType
{
    Mmx,
    Mxx,
    Xxx
};

[[nodiscard]] inline char const * to_c_str( ParallelStrategyType value ) noexcept
{
    switch( value )
    {
    case ParallelStrategyType::Mmx:
        return "mmx";
    case ParallelStrategyType::Mxx:
        return "mxx";
    case ParallelStrategyType::Xxx:
        return "xxx";
    default:
        return "unknown";
    }
}

[[nodiscard]] inline std::string to_string( ParallelStrategyType value ) noexcept
{
    return std::string{ to_c_str( value ) };
}

[[nodiscard]] inline ParallelStrategyType to_parallel_strategy_type( char const * str ) noexcept
{
    if ( std::strcmp( str, "mxx" ) == 0 )
    {
        return ParallelStrategyType::Mxx;
    }
    if ( std::strcmp( str, "xxx" ) == 0 )
    {
        return ParallelStrategyType::Xxx;
    }
    return ParallelStrategyType::Mmx;
}

[[nodiscard]] inline ParallelStrategyType to_parallel_strategy_type( std::string const& str ) noexcept
{
    return to_parallel_strategy_type( str.c_str() );
}

} // end of namespace vortex::runner::config

#pragma clang diagnostic pop
