// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <ostream>
#include <string_view>
#include <span>

#include "core/common/types.hpp"

namespace vortex::turb::legacy::settings::stat
{

struct ExecutionSettings
{
    std::string_view job_name = std::string_view{};
    std::string_view grant_no = std::string_view{};
    i32 cpu_node_count = 1;
    f64 wct_limit = 60.0;
    i32 process_count = 1;
    bool is_node_overcommit_enabled = bool{};
    void * m_data_p = nullptr;

    [[nodiscard]] std::string to_string() const;
    std::ostream& stringify( std::ostream& os, int indent_size, int indent_level ) const;

    friend std::ostream& operator<<( std::ostream& os, ExecutionSettings const& s );

}; // end of class ExecutionSettings

} // end of namespace vortex::turb::legacy::settings::stat
