// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <string_view>
#include <span>

#include "core/common/types.hpp"
#include "core/settings/static_settings_data_storage.hpp"
#include "turb/legacy/settings/metadata.hpp"
#include "turb/legacy/settings/stat/metadata.hpp"
#include "turb/legacy/settings/enums/sim_method.hpp"
#include "turb/legacy/settings/enums/particle_mode.hpp"
#include "turb/legacy/settings/enums/gravity_mode.hpp"
#include "turb/legacy/settings/enums/particle_twc_kernel_type.hpp"

namespace vortex::turb::legacy::settings
{

[[nodiscard]] stat::Metadata to_static( Metadata const& s, [[maybe_unused]] core::settings::StaticSettingsDataStorage& data_storage );
[[nodiscard]] stat::Metadata to_static_unchecked( Metadata const& s, [[maybe_unused]] core::settings::StaticSettingsDataStorage& data_storage );
[[nodiscard]] stat::Metadata to_static_unchecked( Metadata const& s, [[maybe_unused]] core::settings::StaticSettingsDataStorage& data_storage, [[maybe_unused]] void ** data_offset_pp );

} // end of namespace vortex::turb::legacy::settings
