// 
// Source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "runner/config/test_stage.hpp"

#include <nlohmann/json.hpp>

namespace vortex::runner::config
{

TestStage::TestStage( nlohmann::json * data_p )
:   m_data_p( data_p )
{
    // add initial validation
}

// "name" property

[[nodiscard]] std::string_view TestStage::name() const
{
    if ( m_data_p == nullptr ) return default_name();
    auto it = m_data_p->find( "name" );
    if ( it == m_data_p->end() || it->is_null() ) return default_name();
    return std::string_view{ it->template get_ref<std::string const&>() };
}

// "settings" property

[[nodiscard]] /* TODO: settings opaque interface */ void * TestStage::settings() const
{
    if ( m_data_p == nullptr ) throw std::runtime_error( "TestStage: cannot get default value of unset property with settings type." );
    return nullptr;
}


} // end of namespace vortex::runner::config
