// 
// Source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "runner/config/test_stage.hpp"

namespace vortex::runner::config
{

TestStage::TestStage( nlohmann::json * data_p )
:   m_data_p( data_p )
{
    // add initial validation
}

} // end of namespace vortex::runner::config
