// 
// Source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "runner/config/test_fixture.hpp"

#include <nlohmann/json.hpp>

namespace vortex::runner::config
{

TestFixture::TestFixture( nlohmann::json * data_p )
:   m_data_p( data_p )
{
    // add initial validation
}

// "name" property

[[nodiscard]] std::string_view TestFixture::name() const
{
    if ( m_data_p == nullptr ) return default_name();
    auto it = m_data_p->find( "name" );
    if ( it == m_data_p->end() || it->is_null() ) return default_name();
    return std::string_view{ it->template get_ref<std::string const&>() };
}

// "root_path" property

[[nodiscard]] std::string_view TestFixture::root_path() const
{
    if ( m_data_p == nullptr ) return default_root_path();
    auto it = m_data_p->find( "root_path" );
    if ( it == m_data_p->end() || it->is_null() ) return default_root_path();
    return std::string_view{ it->template get_ref<std::string const&>() };
}

// "default_settings" property

[[nodiscard]] /* TODO: settings opaque interface */ void * TestFixture::default_settings() const
{
    if ( m_data_p == nullptr ) throw std::runtime_error( "TestFixture: cannot get default value of unset property with settings type." );
    return nullptr;
}

// "test_cases" property

[[nodiscard]] /* TODO: settings dynamic class */ void * TestFixture::test_cases() const
{
    if ( m_data_p == nullptr ) return default_test_cases();
    return nullptr;
}

// "test_stages" property

[[nodiscard]] /* TODO: settings dynamic class */ void * TestFixture::test_stages() const
{
    if ( m_data_p == nullptr ) return default_test_stages();
    return nullptr;
}


} // end of namespace vortex::runner::config
