// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json_fwd.hpp>

namespace vortex::turb::legacy::settings
{

class ExecutionSettings
{
public:
    explicit ExecutionSettings( nlohmann::json * data_p );

private:
    nlohmann::json * m_data_p = nullptr;
}; // end of class ExecutionSettings

} // end of namespace vortex::turb::legacy::settings
