// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

namespace vortex::turb::legacy::settings
{

class Metadata
{
    // TODO
}; // end of class Metadata

} // end of namespace vortex::turb::legacy::settings
