// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

namespace vortex::turb::legacy::settings
{

class Settings
{
    // TODO
}; // end of class Settings

} // end of namespace vortex::turb::legacy::settings
