// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <cstring>
#include <string>

namespace vortex::turb::legacy::settings
{

enum class DragType
{
    Stokes,
    Nonlinear
};

[[nodiscard]] inline constexpr char const * to_c_str( DragType value ) noexcept
{
    switch( value )
    {
    case DragType::Stokes:
        return "stokes";
    case DragType::Nonlinear:
        return "nonlinear";
    default:
        return "unknown";
    }
}

[[nodiscard]] inline std::string to_string( DragType value ) noexcept
{
    return std::string{ to_c_str( value ) };
}

[[nodiscard]] inline constexpr DragType to_drag_type( char const * str ) noexcept
{
    if ( std::strcmp( str, "nonlinear" ) == 0 )
    {
        return DragType::Nonlinear;
    }
    return DragType::Stokes;
}

[[nodiscard]] inline DragType to_drag_type( std::string const& str ) noexcept
{
    return to_drag_type( str.c_str() );
}

} // end of namespace vortex::turb::legacy::settings
