// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json.hpp>

#include "turb/legacy/settings/enums/forcing_type.hpp"

namespace vortex::turb::legacy::settings
{

NLOHMANN_JSON_SERIALIZE_ENUM( ForcingType,
{
    { ForcingType::Deterministic, "deterministic" },
    { ForcingType::Stochastic, "stochastic" },
})

} // end of namespace vortex::turb::legacy::settings
