// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <cstring>
#include <string>

namespace vortex::turb::legacy::settings
{

enum class GravityMode
{
    None,
    Vertical,
    Horizontal
};

[[nodiscard]] inline char const * to_c_str( GravityMode value ) noexcept
{
    switch( value )
    {
    case GravityMode::None:
        return "none";
    case GravityMode::Vertical:
        return "vertical";
    case GravityMode::Horizontal:
        return "horizontal";
    }
        return "unknown";
}

[[nodiscard]] inline std::string to_string( GravityMode value ) noexcept
{
    return std::string{ to_c_str( value ) };
}

[[nodiscard]] inline GravityMode to_gravity_mode( char const * str ) noexcept
{
    if ( std::strcmp( str, "vertical" ) == 0 )
    {
        return GravityMode::Vertical;
    }
    if ( std::strcmp( str, "horizontal" ) == 0 )
    {
        return GravityMode::Horizontal;
    }
    return GravityMode::None;
}

[[nodiscard]] inline GravityMode to_gravity_mode( std::string const& str ) noexcept
{
    return to_gravity_mode( str.c_str() );
}

} // end of namespace vortex::turb::legacy::settings
