// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json.hpp>

#include "turb/legacy/settings/enums/particle_mode.hpp"

namespace vortex::turb::legacy::settings
{

NLOHMANN_JSON_SERIALIZE_ENUM( ParticleMode,
{
    { ParticleMode::None, "none" },
    { ParticleMode::Owc, "owc" },
    { ParticleMode::Twc, "twc" },
})

} // end of namespace vortex::turb::legacy::settings
