// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json.hpp>

#include "turb/legacy/settings/enums/particle_twc_kernel_type.hpp"

namespace vortex::turb::legacy::settings
{

NLOHMANN_JSON_SERIALIZE_ENUM( ParticleTwcKernelType,
{
    { ParticleTwcKernelType::Pnn, "pnn" },
    { ParticleTwcKernelType::Pic, "pic" },
})

} // end of namespace vortex::turb::legacy::settings
