// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json.hpp>

#include "turb/legacy/settings/enums/sim_method.hpp"

namespace vortex::turb::legacy::settings
{

NLOHMANN_JSON_SERIALIZE_ENUM( SimMethod,
{
    { SimMethod::Dns, "dns" },
    { SimMethod::Les, "les" },
    { SimMethod::Fdns, "fdns" },
})

} // end of namespace vortex::turb::legacy::settings
