// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include "runner/config/test_fixture.hpp"

TEST_CASE("TestFixture - Sample Test", "[sample]")
{
    vortex::runner::config::TestFixture();

    REQUIRE(true);
}
