// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include "runner/config/test_case.hpp"

TEST_CASE("TestCase - Sample Test", "[sample]")
{
    vortex::runner::config::TestCase( nullptr );

    REQUIRE(true);
}
