// 
// Source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "turb/legacy/settings/stat/settings_conversion.hpp"

namespace vortex::turb::legacy::settings
{

[[nodiscard]] stat::Settings to_static( [[maybe_unused]] Settings const& s, [[maybe_unused]] core::settings::StaticSettingsDataStorage& data_storage )
{
    // TODO - add implementation
    return stat::Settings{};
}

} // end of namespace vortex::turb::legacy::settings
