// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

namespace vortex::runner::config
{

class TestStage
{
    // TODO
}; // end of class TestStage

} // end of namespace vortex::runner::config
