// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json_fwd.hpp>

#include "core/common/types.hpp"

namespace vortex::runner::config
{

class TestStage
{
public:
    explicit TestStage( nlohmann::json * data_p );

public:
    // "name" property
    [[nodiscard]] std::string_view name() const;
    [[nodiscard]] constexpr std::string_view default_name() const noexcept
    {
        return std::string_view{};
    }

    // "settings" property
    [[nodiscard]] /* TODO: settings opaque interface */ void * settings() const;


private:
    nlohmann::json * m_data_p = nullptr;
}; // end of class TestStage

} // end of namespace vortex::runner::config
