// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json_fwd.hpp>

#include "core/common/types.hpp"
#include "runner/config/test_case.hpp"
#include "runner/config/test_stage.hpp"

namespace vortex::runner::config
{

class TestFixture
{
public:
    explicit TestFixture( nlohmann::json * data_p );

public:
    // "name" property
    [[nodiscard]] std::string_view name() const;
    [[nodiscard]] constexpr std::string_view default_name() const noexcept
    {
        return std::string_view{};
    }

    // "root_path" property
    [[nodiscard]] std::string_view root_path() const;
    [[nodiscard]] constexpr std::string_view default_root_path() const noexcept
    {
        return ".";
    }

    // "default_settings" property
    [[nodiscard]] /* TODO: settings opaque interface */ void * default_settings() const;

    // "test_cases" property
    [[nodiscard]] /* TODO: settings dynamic class */ void * test_cases() const;
    [[nodiscard]] constexpr /* TODO: settings dynamic class */ void * default_test_cases() const noexcept
    {
        return /* TODO: settings dynamic class constructor from nullptr */ nullptr;
    }

    // "test_stages" property
    [[nodiscard]] /* TODO: settings dynamic class */ void * test_stages() const;
    [[nodiscard]] constexpr /* TODO: settings dynamic class */ void * default_test_stages() const noexcept
    {
        return /* TODO: settings dynamic class constructor from nullptr */ nullptr;
    }


private:
    nlohmann::json * m_data_p = nullptr;
}; // end of class TestFixture

} // end of namespace vortex::runner::config
