// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include <nlohmann/json_fwd.hpp>

namespace vortex::runner::config
{

class TestFixture
{
public:
    explicit TestFixture( nlohmann::json * data_p );

private:
    nlohmann::json * m_data_p = nullptr;
}; // end of class TestFixture

} // end of namespace vortex::runner::config
