// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#pragma once

#include "core/settings/json/settings_provider.hpp"
#include "turb/legacy/settings/settings.hpp"

namespace vortex::turb::legacy::settings::providers
{

class JsonSettingsProvider : public core::settings::json::SettingsProvider
{
public:
    using core::settings::json::SettingsProvider::SettingsProvider;

    JsonSettingsProvider( JsonSettingsProvider const& ) = delete;
    JsonSettingsProvider& operator=( JsonSettingsProvider const& ) = delete;
    JsonSettingsProvider( JsonSettingsProvider && ) = delete;
    JsonSettingsProvider& operator=( JsonSettingsProvider && ) = delete;

    ~JsonSettingsProvider() noexcept = default;

public:
    [[nodiscard]] Settings get_settings( std::string const& key );
    [[nodiscard]] Settings get_settings( std::string const& key, std::istream& is );
    [[nodiscard]] Settings get_settings( std::string const& key, std::filesystem::path const& path );
    [[nodiscard]] Settings get_settings( std::filesystem::path const& path );

}; // end of class JsonSettingsProvider

} // end of namespace vortex::turb::legacy::settings::providers
