// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "turb/legacy/settings/static/execution_settings.hpp"

TEST_CASE( "ExecutionSettings - conversion to string", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "ExecutionSettings - conversion to string - display all", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "ExecutionSettings - conversion to string - extra indent size", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "ExecutionSettings - conversion to string - extra indent level", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "ExecutionSettings - conversion to string for empty", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "ExecutionSettings - property: \"job_name\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "ExecutionSettings - property: \"grant_no\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "ExecutionSettings - property: \"cpu_node_count\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "ExecutionSettings - property: \"wct_limit\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "ExecutionSettings - property: \"process_count\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "ExecutionSettings - property: \"is_node_overcommit_enabled\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}

