// 
// Unit test source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "turb/legacy/settings/static/settings.hpp"

TEST_CASE( "Settings - conversion to string", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Settings - conversion to string - display all", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Settings - conversion to string - extra indent size", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Settings - conversion to string - extra indent level", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Settings - conversion to string for empty", "[settings][.][!mayfail]" )
{
    // TODO - add conversion to string tests for generated static setting classes
    REQUIRE( false );
}

TEST_CASE( "Settings - property: \"metadata\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "Settings - property: \"parameters\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}
TEST_CASE( "Settings - property: \"execution_settings\" - static", "[settings]" )
{
    // TODO - supply test implementation
    REQUIRE( true );
}

