[__metadata__]
module = "test_stage"
package = "runner"
namespace = ["config"]
skip_static_generation = true
languages = ["cpp"]


[name]
type = "string"
is_required = true

[settings]
type = "settings"
