[__metadata__]
module = "test_stage"
package = "runner"
namespace = ["config"]
skip_static_generation = true
languages = ["cpp"]


[[__includes__]]
from = "turb-legacy-settings"
import.modules = [ "settings" ]


[name]
type = "string"

[settings]
type = "module"
module.name = "settings"
