[__metadata__]
module = "test_case"
package = "runner"
namespace = ["config"]
skip_static_generation = true
languages = ["cpp"]


[name]
type = "string"

[template_name]
type = "string"

[settings]
type = "settings"

[parallel_strategy]
type = "enum"
enum.name = "parallel_strategy_type"
enum.values = [ "MMX", "MXX", "XXX" ]

[stages]
type = "string"
is_array = true

[process_count]
type = "i32"
