[__metadata__]
module = "test_case"
package = "runner"
namespace = ["config"]
skip_static_generation = true
languages = ["cpp"]


[name]
type = "string"
requires = [ "nonempty" ]
is_required = true

[template_name]
type = "string"
requires = [ "nonempty" ]

[settings]
type = "settings"

[parallel_strategy]
type = "enum"
enum.name = "parallel_strategy_type"
enum.values = [ "mmx", "mxx", "xxx" ]

[stages]
type = "string"
is_array = true
requres = [ "unique", "*range(max=@{process_count},mapping=@{settings.execution_settings_process_count})" ]

[process_count]
type = "i32"
default = 1
requires = [ "range(min=1)", "*range(min=@{settings.execution_settings.process_count})" ]
