[__metadata__]
module = "test_case"
package = "runner"
namespace = ["config"]
skip_static_generation = true
languages = ["cpp"]


[[__includes__]]
from = "turb-legacy-settings"
import.modules = [ "settings" ]


[name]
type = "string"

[template]
type = "string"

[settings]
type = "module"
module.name = "settings"

[parallel_strategy]
type = "enum"
enum.name = "parallel_strategy_type"
enum.values = [ "MMX", "MXX", "XXX" ]

[stages]
type = "string"
is_array = true

[process_count]
type = "i32"
