[__metadata__]
module = "metadata"
package = "*turb"
namespace = [ "legacy", "settings" ]


[sim_method]
type = "enum"
enum.name = "sim_method"
enum.values = ["dns", "les", "fdns"]

[particle_mode]
type = "enum"
enum.name = "particle_mode"
enum.values = ["none", "owc", "twc"]

[gravity_type]
type = "enum"
enum.name = "gravity_mode"
enum.values = ["none", "vertical", "horizontal"]

[particle_kernel_type]
type = "enum"
enum.name = "particle_twc_kernel_type"
enum.values = ["pnn", "pic"]

[k_filter]
type = "i32"

[C_K]
type = "real"
default = 2.5

[target_Phi]
type = "real"

[superpart_factor]
type = "real"
default = 1

[src_flow_path]
type = "path"

[src_part_path]
type = "path"

[part_output_delay]
type = "i32"

[is_perf_full_profile_enabled]
type = "boolean"

[is_perf_simple_enabled]
type = "boolean"

[is_perf_part_dist_enabled]
type = "boolean"

[perf_full_start]
type = "i32"

[perf_full_end]
type = "i32"

[part_perf_interval]
type = "i32"
