[__metadata__]
module = "settings"
package = "*turb"
namespace = [ "legacy", "settings" ]


[[__includes__]]
from = "turb-legacy-metadata"
import.modules = [ "metadata" ]

[[__includes__]]
from = "turb-legacy-parameters"
import.modules = [ "parameters" ]

[[__includes__]]
from = "turb-legacy-execution-settings"
import.modules = [ "execution_settings" ]


[metadata]
type = "module"

[parameters]
type = "module"

[execution_settings]
type = "module"
