[__metadata__]
module = "execution_settings"
package = "*turb"
namespace = [ "legacy", "settings" ]


[job_name]
type = "string"
default = "default_job"
requires = [ "nonemty" ]

[grant_no]
type = "string"
requires = [ "#nonempty" ]

[cpu_node_count]
type = "i32"
default = 1
requires=[ "range(min=1,max=${CPU_NODE_COUNT_MAX:null}" ]

[wct_limit]
type = "f64"
default = "60.0"
requires=[ "range(min=5.0,max=${WCT_LIMIT_MAX:null}" ]

[process_count]
type = "i32"
default = 1
requires=[ "range(min=1)" ]

[is_node_overcommit_enabled]
type = "boolean"
