[__metadata__]
module = "execution_settings"
package = "*turb"
namespace = [ "legacy", "settings" ]


[job_name]
type = "string"

[grant_no]
type = "string"

[cpu_node_count]
type = "i32"

[wct_limit]
type = "f64"

[process_count]
type = "i32"

[is_node_overcommit_enabled]
type = "boolean"
