// 
// Source file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "turb/legacy/settings/metadata.hpp"

namespace vortex::turb::legacy::settings
{

Metadata::Metadata( nlohmann::json * data_p )
:   m_data_p( data_p )
{
    // add initial validation
}

} // end of namespace vortex::turb::legacy::settings
