// 
// Header file auto-generated by VORTEX SETTINGS WIZARD
// 
// TODO: Just testing
// 

#include "turb/legacy/settings/settings.hpp"

namespace vortex::turb::legacy::settings
{

// TODO

} // end of namespace vortex::turb::legacy::settings
