name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-13
        compiler:
          - llvm-18
          - llvm-19
          - gcc-11
          - gcc-12
          - gcc-13
        mpi:
          - mpich
          - openmpi
          - intelmpi

        exclude:
          # catch2 import via Conan causes issues with gcc-13
          - os: macos-13
            compiler: gcc-13
          # Intel MPI not supported on Apple hardware
          - os: macos-13
            mpi: intelmpi
          # temporary disable Clang for MacOS due to problems in compiler detection
          # - TODO: improve 'conan profile detect' and conan profile handling
          - os: macos-13
            compiler: llvm-18
          - os: macos-13
            compiler: llvm-19

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: 3.31.1
          ninja: 1.12.1
          conan: 2.11.0

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Setup Dependencies via Conan
        run: |
          conan profile detect
          conan install conanfile.txt --build=missing

      - name: Configure CMake Project
        run: |
          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build Project
        run: |
          cmake --build ./build -v

      - name: Run Tests
        working-directory: ./build
        run: |
          ctest --output-on-failure
