name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - llvm-17
          - gcc-13
          
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: 3.22.1
          ninja: 1.10.1
          conan: true
          cppcheck: true
          clangtidy: 17

      - name: Setup Dependencies via Conan
        run: |
          conan install conanfile.txt --build=missing

      - name: Configure CMake Project
        run: |
          cmake -S -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build Project
        run: |
          cmake --build ./build -v

      - name: Run Tests
        working-directory: ./build
        run: |
          ctest
          