name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - llvm-17
          - gcc-13
        mpi:
          - mpich
          - openmpi
          - intelmpi

        # TODO: investigate why this does not work
        exclude:
          - compiler: llvm-17
            mpi: mpich
          
    steps:
      - uses: actions/checkout@v4

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: 3.22.1
          ninja: 1.10.1
          conan: 2.2.3

      - name: Setup Dependencies via Conan
        run: |
          conan profile detect
          conan install conanfile.txt --build=missing

      - name: Configure CMake Project
        run: |
          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build Project
        run: |
          cmake --build ./build -v

      - name: Run Tests
        working-directory: ./build
        run: |
          ctest
          